In [2]:
import numpy as np
import pandas as pd

import difflib

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
movies_data = pd.read_csv('movies_1.csv')

In [4]:
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [5]:
movies_data.shape

(4803, 24)

#### Feature selection 

In [6]:
movies_data_features = movies_data[["genres","keywords","overview","tagline","cast","director"]]

In [7]:
movies_data_features.fillna("", inplace = True)

C:\Users\HP\AppData\Local\Temp\ipykernel_5152\4102732691.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_data_features.fillna("", inplace = True)


In [8]:
movies_data_features.isnull().sum()

genres      0
keywords    0
overview    0
tagline     0
cast        0
director    0
dtype: int64

In [9]:
combine_movies_data_features = movies_data_features["genres"] + " " + movies_data_features["keywords"] + " " + movies_data_features["overview"] + " " + movies_data_features["tagline"]+ " " + movies_data_features["cast"]+ " " + movies_data_features["director"]
combine_movies_data_features

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      When ambitious New York attorney Sam is sent...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object

#### Converting combined text features to vectors

In [10]:
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combine_movies_data_features)

In [11]:
print(feature_vectors)

  (0, 4288)	0.13213124585063996
  (0, 14180)	0.08418056281586364
  (0, 23134)	0.1498786462809525
  (0, 17784)	0.12285843797047787
  (0, 15569)	0.171366691592621
  (0, 25868)	0.11590870590502833
  (0, 29614)	0.15064979633862852
  (0, 24802)	0.158925784923944
  (0, 23578)	0.16802034155542864
  (0, 30543)	0.15064979633862852
  (0, 30145)	0.18243919685121024
  (0, 23619)	0.11047375838269538
  (0, 19410)	0.0318696249813729
  (0, 30121)	0.07272849549697494
  (0, 9065)	0.14505772980982928
  (0, 5245)	0.16506865163441015
  (0, 1014)	0.12285843797047787
  (0, 1243)	0.05270709034262741
  (0, 21523)	0.1665010643166998
  (0, 1281)	0.03195190270050669
  (0, 19650)	0.1612055740237117
  (0, 10368)	0.13848277654301597
  (0, 2974)	0.09974129089792806
  (0, 27515)	0.14569220419090678
  (0, 2685)	0.09805341831299116
  :	:
  (4802, 27153)	0.05940079357098276
  (4802, 19243)	0.061349419053434766
  (4802, 11941)	0.07829183421073846
  (4802, 29680)	0.07735547381237222
  (4802, 9346)	0.07104321122746965
  (48

#### Getting similarity score

In [12]:
similarity = cosine_similarity(feature_vectors)

In [13]:
print(similarity)

[[1.         0.05083168 0.0332947  ... 0.02749812 0.0304889  0.0072518 ]
 [0.05083168 1.         0.04356836 ... 0.05077045 0.03100979 0.01521198]
 [0.0332947  0.04356836 1.         ... 0.02646984 0.04751623 0.01372603]
 ...
 [0.02749812 0.05077045 0.02646984 ... 1.         0.03481447 0.03546821]
 [0.0304889  0.03100979 0.04751623 ... 0.03481447 1.         0.03098945]
 [0.0072518  0.01521198 0.01372603 ... 0.03546821 0.03098945 1.        ]]


In [14]:
print(similarity.shape)

(4803, 4803)


In [15]:
movie_name = input ('Enter your favorite movie name: ')

Enter your favorite movie name: Disney


In [16]:
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [17]:
find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

['Diner', 'Kinsey', 'Nine']


In [18]:
close_match = find_close_match[0]
print(close_match)

Diner


In [19]:
index_of_the_movie = movies_data[movies_data['title'] == close_match]["index"].values[0]
print(index_of_the_movie)

3602


In [20]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.014963618458699654), (1, 0.02721258921756868), (2, 0.02518838732734784), (3, 0.016837648884380742), (4, 0.02278751123947414), (5, 0.016329068172502292), (6, 0.028136651036222145), (7, 0.02588522468988057), (8, 0.023708147462640765), (9, 0.016235815478786796), (10, 0.02832453579206651), (11, 0.032352042281072), (12, 0.022474325648564587), (13, 0.01564925354593497), (14, 0.04190219857205259), (15, 0.033056007126192936), (16, 0.01673363525614089), (17, 0.02380568212198905), (18, 0.059465005211019085), (19, 0.04508475403367543), (20, 0.0337063731825777), (21, 0.0201127774220185), (22, 0.03276212568735373), (23, 0.022159230300034118), (24, 0.012564003914964927), (25, 0.03105841710966916), (26, 0.026049405292148185), (27, 0.018876990609441043), (28, 0.01928095193207537), (29, 0.02905594871330987), (30, 0.016523215524848107), (31, 0.020832677490838156), (32, 0.030409962719124786), (33, 0.02713302800506015), (34, 0.029238630740036374), (35, 0.025591052578883285), (36, 0.0220674300337990

In [21]:
len(sorted_similar_movies)

4803

In [21]:
sorted_similar_movies = sorted(similarity_score, key = lambda x: x[1], reverse = True)
print(sorted_similar_movies)

[(3602, 1.0000000000000002), (4460, 0.20771815038446045), (1791, 0.19092593750831946), (2281, 0.13293472487203095), (1374, 0.12249411578111503), (1105, 0.12031264914550485), (3808, 0.11904350206573522), (1612, 0.11754357108773733), (1512, 0.11294378117669979), (2604, 0.11003649762266297), (2820, 0.10196116286936131), (3925, 0.10023665007280586), (2813, 0.09790093865458326), (4082, 0.09050021544623718), (4496, 0.08806617763272538), (4711, 0.08782479918315587), (4223, 0.0876649955084785), (2007, 0.08570643400143292), (310, 0.08445599256675525), (3247, 0.08444277474057266), (2991, 0.08343428549643343), (1696, 0.0833091892993172), (304, 0.08286405905094284), (1984, 0.08072404178823428), (3977, 0.0806279784675921), (2755, 0.08053839656196032), (3326, 0.08031982136811712), (3127, 0.08007341617852107), (4767, 0.07945984712144868), (1861, 0.07945125214504575), (1869, 0.0791907665777882), (2795, 0.07898188210121579), (3457, 0.07684642159704691), (3287, 0.07634184796241719), (1097, 0.07616164032

In [22]:
print ('Movies suggested for you: \n')

i = 1

for movie in sorted_similar_movies:
    index = movie[0]
    title_from_index = movies_data[movies_data['index'] == index]["title"].values[0]
    if (i<31):
        print(i, '.', title_from_index)
        i+=1

Movies suggested for you: 

1 . Diner
2 . Deterrence
3 . Legion
4 . A Cinderella Story
5 . L.A. Confidential
6 . Sleepers
7 . The Helpers
8 . Larry Crowne
9 . A History of Violence
10 . Here On Earth
11 . Step Up
12 . Whipped
13 . Think Like a Man
14 . Courageous
15 . The Blair Witch Project
16 . Aroused
17 . Buffalo '66
18 . Harley Davidson and the Marlboro Man
19 . In the Heart of the Sea
20 . That Awkward Moment
21 . Bill & Ted's Excellent Adventure
22 . Straight Outta Compton
23 . Hercules
24 . The Thief and the Cobbler
25 . Boynton Beach Club
26 . Earth to Echo
27 . Black November
28 . Beat the World
29 . Run, Hide, Die
30 . The House Bunny


#### Recommendation system

In [ ]:
movie_name = input ('Enter your favorite movie name: ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data['title'] == close_match]["index"].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x: x[1], reverse = True)

print ('Movies suggested for you: \n')

i = 1

for movie in sorted_similar_movies:
    index = movie[0]
    title_from_index = movies_data[movies_data['index'] == index]["title"].values[0]
    if (i<31):
        print(i, '.', title_from_index)
        i+=1